insert into subjects values(1,'mathematics');
insert into subjects values(2,'science');
insert into subjects values(3,'physical education');
insert into subjects values(4,'art');
insert into subjects values(5,'english');
insert into subjects values(6,'spanish');
insert into subjects values(7,'french');
insert into subjects values(8,'polish');
insert into subjects values(9,'german');
insert into subjects values(10,'chinese');
insert into subjects values(11,'russian');
insert into subjects values(12,'geography');
insert into subjects values(13,'physics');
insert into subjects values(14,'chemistry');
insert into subjects values(15,'biology');
insert into subjects values(16,'computer science');
insert into subjects values(17,'religion');
insert into subjects values(18,'history');
insert into subjects values(19,'social studies');
insert into subjects values(20,'safety education');

INSERT INTO "teachers" (email,name,surname) VALUES ('pretium.aliquet.metus@vulputatemaurissagittis.ca','Eagan','Cook');
INSERT INTO "teachers" (email,name,surname) VALUES ('erat@lobortisnisinibh.net','Adam','Harris');
INSERT INTO "teachers" (email,name,surname) VALUES ('molestie@magna.net','Caleb','Powers');
INSERT INTO "teachers" (email,name,surname) VALUES ('massa@Maurisquis.org','Xander','Morton');
INSERT INTO "teachers" (email,name,surname) VALUES ('senectus.et@gravida.co.uk','Brady','Melton');
INSERT INTO "teachers" (email,name,surname) VALUES ('nonummy.ut@et.org','Alan','Barton');
INSERT INTO "teachers" (email,name,surname) VALUES ('nec.imperdiet@Maurismolestie.ca','Basil','Thornton');
INSERT INTO "teachers" (email,name,surname) VALUES ('ridiculus@inceptoshymenaeos.co.uk','Emerson','Campbell');
INSERT INTO "teachers" (email,name,surname) VALUES ('aliquam.enim@acorciUt.org','Benjamin','Douglas');
INSERT INTO "teachers" (email,name,surname) VALUES ('libero.at@Quisquetincidunt.co.uk','Camden','Rich');
INSERT INTO "teachers" (email,name,surname) VALUES ('id.erat@orci.org','Reuben','Heath');
INSERT INTO "teachers" (email,name,surname) VALUES ('ante.iaculis.nec@varius.edu','George','Short');
INSERT INTO "teachers" (email,name,surname) VALUES ('dui@ipsumnuncid.org','Cullen','Kinney');
INSERT INTO "teachers" (email,name,surname) VALUES ('Nam.ligula@sit.edu','Ignatius','Cardenas');
INSERT INTO "teachers" (email,name,surname) VALUES ('auctor@pede.org','Lawrence','Golden');
INSERT INTO "teachers" (email,name,surname) VALUES ('dis.parturient.montes@elit.co.uk','Kaseem','Rice');
INSERT INTO "teachers" (email,name,surname) VALUES ('faucibus.leo.in@consequatnec.edu','Philip','Flowers');
INSERT INTO "teachers" (email,name,surname) VALUES ('inceptos.hymenaeos.Mauris@iaculisodio.com','Berk','Mcdonald');
INSERT INTO "teachers" (email,name,surname) VALUES ('In.ornare.sagittis@vestibulum.net','Grant','Bush');
INSERT INTO "teachers" (email,name,surname) VALUES ('pellentesque.tellus.sem@mipede.co.uk','Clark','Lancaster');

insert into teacher_subjects values(1,1);
insert into teacher_subjects values(1,13);
insert into teacher_subjects values(2,14);
insert into teacher_subjects values(3,20);
insert into teacher_subjects values(3,17);
insert into teacher_subjects values(5,4);
insert into teacher_subjects values(6,1);
insert into teacher_subjects values(7,1);
insert into teacher_subjects values(7,16);
insert into teacher_subjects values(7,6);
insert into teacher_subjects values(7,4);
insert into teacher_subjects values(8,8);
insert into teacher_subjects values(8,11);
insert into teacher_subjects values(9,12);
insert into teacher_subjects values(10,10);
insert into teacher_subjects values(11,14);
insert into teacher_subjects values(11,15);
insert into teacher_subjects values(12,1);
insert into teacher_subjects values(12,2);
insert into teacher_subjects values(13,9);
insert into teacher_subjects values(13,17);
insert into teacher_subjects values(14,19);
insert into teacher_subjects values(14,18);
insert into teacher_subjects values(15,13);
insert into teacher_subjects values(15,14);
insert into teacher_subjects values(15,15);
insert into teacher_subjects values(15,2);
insert into teacher_subjects values(16,8);
insert into teacher_subjects values(16,9);
insert into teacher_subjects values(17,4);
insert into teacher_subjects values(17,17);
insert into teacher_subjects values(18,5);
insert into teacher_subjects values(18,8);
insert into teacher_subjects values(19,5);
insert into teacher_subjects values(19,11);
insert into teacher_subjects values(20,1);
insert into teacher_subjects values(20,3);
